### ISSUE TITLE
DEMO运行失败，APPID为空，是需要申请什么东西吗？

### ISSUE THREAD

**Issue by Yangqingchun** [tencentmusic/qqmusic-innovocation-openapi-sdk-android-demo#3]
![1717639801941](https://github.com/tencentmusic/qqmusic-innovocation-openapi-sdk-android-demo/assets/33993115/48b68f74-c19f-48b9-85fc-f077664a7c8f)

**Comment by tannyli-tme** [comment]
你好，初始化方法需要设置官网上申请的APPID和APPKEY
